// This file is auto-generated by @hey-api/openapi-ts

import { type Options, brandsApiBrandsGet, getPhoneBrandApiDeviceBrandGet, exportCsvApiExportCsvPost, testApiTestGet, testSearchApiTestSearchPost } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { BrandsApiBrandsGetData, GetPhoneBrandApiDeviceBrandGetData, ExportCsvApiExportCsvPostData, ExportCsvApiExportCsvPostResponse, TestApiTestGetData, TestSearchApiTestSearchPostData, TestSearchApiTestSearchPostError, TestSearchApiTestSearchPostResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const brandsApiBrandsGetQueryKey = (options?: Options<BrandsApiBrandsGetData>) => createQueryKey('brandsApiBrandsGet', options);

/**
 * Brands
 */
export const brandsApiBrandsGetOptions = (options?: Options<BrandsApiBrandsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await brandsApiBrandsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: brandsApiBrandsGetQueryKey(options)
    });
};

export const getPhoneBrandApiDeviceBrandGetQueryKey = (options: Options<GetPhoneBrandApiDeviceBrandGetData>) => createQueryKey('getPhoneBrandApiDeviceBrandGet', options);

/**
 * Get Phone Brand
 */
export const getPhoneBrandApiDeviceBrandGetOptions = (options: Options<GetPhoneBrandApiDeviceBrandGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPhoneBrandApiDeviceBrandGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPhoneBrandApiDeviceBrandGetQueryKey(options)
    });
};

export const exportCsvApiExportCsvPostQueryKey = (options?: Options<ExportCsvApiExportCsvPostData>) => createQueryKey('exportCsvApiExportCsvPost', options);

/**
 * Export Csv
 */
export const exportCsvApiExportCsvPostOptions = (options?: Options<ExportCsvApiExportCsvPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportCsvApiExportCsvPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportCsvApiExportCsvPostQueryKey(options)
    });
};

/**
 * Export Csv
 */
export const exportCsvApiExportCsvPostMutation = (options?: Partial<Options<ExportCsvApiExportCsvPostData>>): UseMutationOptions<ExportCsvApiExportCsvPostResponse, AxiosError<DefaultError>, Options<ExportCsvApiExportCsvPostData>> => {
    const mutationOptions: UseMutationOptions<ExportCsvApiExportCsvPostResponse, AxiosError<DefaultError>, Options<ExportCsvApiExportCsvPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await exportCsvApiExportCsvPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const testApiTestGetQueryKey = (options?: Options<TestApiTestGetData>) => createQueryKey('testApiTestGet', options);

/**
 * Test
 */
export const testApiTestGetOptions = (options?: Options<TestApiTestGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await testApiTestGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: testApiTestGetQueryKey(options)
    });
};

export const testSearchApiTestSearchPostQueryKey = (options: Options<TestSearchApiTestSearchPostData>) => createQueryKey('testSearchApiTestSearchPost', options);

/**
 * Test Search
 */
export const testSearchApiTestSearchPostOptions = (options: Options<TestSearchApiTestSearchPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await testSearchApiTestSearchPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: testSearchApiTestSearchPostQueryKey(options)
    });
};

/**
 * Test Search
 */
export const testSearchApiTestSearchPostMutation = (options?: Partial<Options<TestSearchApiTestSearchPostData>>): UseMutationOptions<TestSearchApiTestSearchPostResponse, AxiosError<TestSearchApiTestSearchPostError>, Options<TestSearchApiTestSearchPostData>> => {
    const mutationOptions: UseMutationOptions<TestSearchApiTestSearchPostResponse, AxiosError<TestSearchApiTestSearchPostError>, Options<TestSearchApiTestSearchPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await testSearchApiTestSearchPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};