// This file is auto-generated by @hey-api/openapi-ts

import { type Options, brandsApiBrandsGet, getPhoneBrandApiDeviceBrandGet, parserApiParserGet, getPhoneBrandApiExportCsvGet, readRootGet } from '../sdk.gen';
import { queryOptions } from '@tanstack/react-query';
import type { BrandsApiBrandsGetData, GetPhoneBrandApiDeviceBrandGetData, ParserApiParserGetData, GetPhoneBrandApiExportCsvGetData, ReadRootGetData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const brandsApiBrandsGetQueryKey = (options?: Options<BrandsApiBrandsGetData>) => createQueryKey('brandsApiBrandsGet', options);

/**
 * Brands
 */
export const brandsApiBrandsGetOptions = (options?: Options<BrandsApiBrandsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await brandsApiBrandsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: brandsApiBrandsGetQueryKey(options)
    });
};

export const getPhoneBrandApiDeviceBrandGetQueryKey = (options: Options<GetPhoneBrandApiDeviceBrandGetData>) => createQueryKey('getPhoneBrandApiDeviceBrandGet', options);

/**
 * Get Phone Brand
 */
export const getPhoneBrandApiDeviceBrandGetOptions = (options: Options<GetPhoneBrandApiDeviceBrandGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPhoneBrandApiDeviceBrandGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPhoneBrandApiDeviceBrandGetQueryKey(options)
    });
};

export const parserApiParserGetQueryKey = (options?: Options<ParserApiParserGetData>) => createQueryKey('parserApiParserGet', options);

/**
 * Parser
 */
export const parserApiParserGetOptions = (options?: Options<ParserApiParserGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await parserApiParserGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: parserApiParserGetQueryKey(options)
    });
};

export const getPhoneBrandApiExportCsvGetQueryKey = (options?: Options<GetPhoneBrandApiExportCsvGetData>) => createQueryKey('getPhoneBrandApiExportCsvGet', options);

/**
 * Get Phone Brand
 */
export const getPhoneBrandApiExportCsvGetOptions = (options?: Options<GetPhoneBrandApiExportCsvGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPhoneBrandApiExportCsvGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPhoneBrandApiExportCsvGetQueryKey(options)
    });
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readRootGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readRootGetQueryKey(options)
    });
};