// This file is auto-generated by @hey-api/openapi-ts

/**
 * Brands
 */
export type Brands = {
    /**
     * Name
     */
    name: string;
    /**
     * Href
     */
    href: string;
};

export type BrandsPhoneBrandsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/phone/brands';
};

export type BrandsPhoneBrandsGetResponses = {
    /**
     * Response Brands Phone Brands Get
     * Successful Response
     */
    200: Array<Brands>;
};

export type BrandsPhoneBrandsGetResponse = BrandsPhoneBrandsGetResponses[keyof BrandsPhoneBrandsGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};