/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExportRouteImport } from './routes/export'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceBrandSlugRouteImport } from './routes/device/$brandSlug'

const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceBrandSlugRoute = DeviceBrandSlugRouteImport.update({
  id: '/device/$brandSlug',
  path: '/device/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/export': typeof ExportRoute
  '/device/$brandSlug': typeof DeviceBrandSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/export': typeof ExportRoute
  '/device/$brandSlug': typeof DeviceBrandSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/export': typeof ExportRoute
  '/device/$brandSlug': typeof DeviceBrandSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/export' | '/device/$brandSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/export' | '/device/$brandSlug'
  id: '__root__' | '/' | '/about' | '/export' | '/device/$brandSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExportRoute: typeof ExportRoute
  DeviceBrandSlugRoute: typeof DeviceBrandSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$brandSlug': {
      id: '/device/$brandSlug'
      path: '/device/$brandSlug'
      fullPath: '/device/$brandSlug'
      preLoaderRoute: typeof DeviceBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExportRoute: ExportRoute,
  DeviceBrandSlugRoute: DeviceBrandSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
